version: 2.0

unit-test: &unit-test-steps
  steps:
    - attach_workspace:
        at: ~/
    - run:
        name: Running Unit Tests
        command: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

jobs:
  build:
    docker:
      - image: circleci/php:7.2-cli
    steps:
      - checkout
      - run:
          name: Installing packages
          command: |
            composer install
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  unit-test-php-5.6:
    docker:
      - image: circleci/php:5.6-cli
    <<: *unit-test-steps
  unit-test-php-7.0:
    docker:
      - image: circleci/php:7.0-cli
    <<: *unit-test-steps
  unit-test-php-7.1:
    docker:
      - image: circleci/php:7.1-cli
    <<: *unit-test-steps
  unit-test-php-7.2:
    docker:
      - image: circleci/php:7.2-cli
    <<: *unit-test-steps
  unit-test-php-7.3:
    docker:
      - image: circleci/php:7.3-cli
    <<: *unit-test-steps


workflows:
  version: 2
  unit-test:
    jobs:
      - build
      - unit-test-php-5.6:
          requires:
            - build
      - unit-test-php-7.0:
          requires:
            - build
      - unit-test-php-7.1:
          requires:
            - build
      - unit-test-php-7.2:
          requires:
            - build
      - unit-test-php-7.3:
          requires:
            - build

experimental:
  notify:
    branches:
      only:
        - master
